//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatooineModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizens
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Specie { get; set; }
        public int IdRole { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Statuses Status { get; set; }
    }
}
