<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Roles.aspx.cs" Inherits="TatooineCitizensRegistry.Roles" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <div class="row">
    <h3>Tatooine Citizens Roles</h3>
    <asp:GridView runat="server" ID="gvRoles"  AutoGenerateEditButton="true" SelectMethod="gvRoles_GetData"  UpdateMethod="gvRoles_UpdateItem" DeleteMethod="gvRoles_DeleteItem" 
         AutoGenerateColumns="false" OnDataBound="gvRoles_DataBound"
        OnRowCommand="gvRoles_RowCommand" AutoGenerateDeleteButton="true"  DataKeyNames="Id" 
        CssClass="table table-hover table-striped" GridLines="None" >
        <Columns>
            <asp:BoundField HeaderText="Role Name" DataField="RoleName" />
            <asp:ButtonField HeaderText="List Citizens in role." Text="List Citizens in role." CommandName="List" />
        </Columns>
    </asp:GridView>
           <div class="form-group">
                  <a href="#myModal" role="button" class="btn btn-primary" data-toggle="modal">Add new Role</a>
               </div>
         </div>
    <div class="form-group">
        <h4><asp:Label runat="server" ID="lbRol" Visible="false"></asp:Label></h4>
        <asp:GridView runat="server" Visible="false" ID="gvUsers"  CssClass="table table-hover table-striped" GridLines="None" 
         AutoGenerateColumns="false" UseAccessibleHeader="true" >
        <Columns>
            <asp:BoundField HeaderText="Citizen Name" DataField="Name" />
            <asp:BoundField HeaderText="Specie" DataField="Specie" />
        </Columns>
    </asp:GridView>
        <asp:Label runat="server" ID="lbNoCitizens" Visible="false"  CssClass="alert-text">No Citizens in selected row.</asp:Label>
        </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" aria-labelledby="myModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">New Role</h3>
    </div>
    <div class="modal-body">
               <fieldset>
                <label class="control-label">Role Name</label>
                   <asp:TextBox runat="server" ID="tbNewRoleName"  class="form-control" />
                   <asp:RequiredFieldValidator ValidationGroup="addrole" ErrorMessage="Role Name is required." ControlToValidate="tbNewRoleName" runat="server"  Display="Dynamic" SetFocusOnError="True" CssClass="alert-text" />
                <br />
            </fieldset>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <asp:Button Text="Save" runat="server" ID="btAddRole" ValidationGroup="addrole"  class="btn btn-primary" OnClick="btAddRole_Click" />
    </div>
        </div>
</div>
        </div>
</asp:Content>
